# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 975)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 975))
        MainWindow.setMaximumSize(QtCore.QSize(900, 975))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"background: #3E7D96;\n"
"}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background: #4E7D96;\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 16, 861, 911))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(36)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"margin: 0;\n"
"padding: 0;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.labelAmountOfHam = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.labelAmountOfHam.setFont(font)
        self.labelAmountOfHam.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.labelAmountOfHam.setText("")
        self.labelAmountOfHam.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAmountOfHam.setObjectName("labelAmountOfHam")
        self.gridLayout.addWidget(self.labelAmountOfHam, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 16, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(24)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.pushButtonSelectFiles = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.pushButtonSelectFiles.setFont(font)
        self.pushButtonSelectFiles.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSelectFiles.setStyleSheet("QPushButton#pushButtonSelectFiles {\n"
"margin: 0px;\n"
"background: #FF844B;\n"
"color: #0A0D25;\n"
"padding: 10px;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#pushButtonSelectFiles:hover {\n"
"background: #FFA47A;\n"
"cursor: pointer;\n"
"}")
        self.pushButtonSelectFiles.setObjectName("pushButtonSelectFiles")
        self.gridLayout.addWidget(self.pushButtonSelectFiles, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.pushButtonAboutProject = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButtonAboutProject.setFont(font)
        self.pushButtonAboutProject.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAboutProject.setStyleSheet("QPushButton#pushButtonAboutProject {\n"
"color: #E3EDF2;\n"
"background: #4E7D96;\n"
"border: none;\n"
"padding: 10px;\n"
"border-radius: 20px;\n"
"text-decoration: none;\n"
"}\n"
"\n"
"QPushButton#pushButtonAboutProject:hover {\n"
"color: #E3EDF2;\n"
"background: #55859E;\n"
"cursor: pointer;\n"
"text-decoration: underline;\n"
"}")
        self.pushButtonAboutProject.setObjectName("pushButtonAboutProject")
        self.gridLayout.addWidget(self.pushButtonAboutProject, 14, 0, 1, 1)
        self.labelAmountOfSpam = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.labelAmountOfSpam.setFont(font)
        self.labelAmountOfSpam.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.labelAmountOfSpam.setText("")
        self.labelAmountOfSpam.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAmountOfSpam.setObjectName("labelAmountOfSpam")
        self.gridLayout.addWidget(self.labelAmountOfSpam, 4, 0, 1, 1)
        self.pushButtonGitHub = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButtonGitHub.setFont(font)
        self.pushButtonGitHub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGitHub.setStyleSheet("QPushButton#pushButtonGitHub {\n"
"color: #E3EDF2;\n"
"background: #4E7D96;\n"
"border: none;\n"
"padding: 10px;\n"
"border-radius: 20px;\n"
"text-decoration: none;\n"
"}\n"
"\n"
"QPushButton#pushButtonGitHub:hover {\n"
"color: #E3EDF2;\n"
"background: #55859E;\n"
"cursor: pointer;\n"
"text-decoration: underline;\n"
"}")
        self.pushButtonGitHub.setObjectName("pushButtonGitHub")
        self.gridLayout.addWidget(self.pushButtonGitHub, 15, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"color: #FCFAF8;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spam Classifier"))
        self.label.setText(_translate("MainWindow", "Spam Classifier"))
        self.label_8.setText(_translate("MainWindow", "Función de activación para las capas ocultas es: tanh."))
        self.label_2.setText(_translate("MainWindow", "Spam Classifier - By Ismael Avila & Oscar Beltrán © 2023"))
        self.label_3.setText(_translate("MainWindow", "¡El modelo se entrenó por 70,000 épocas!"))
        self.label_5.setText(_translate("MainWindow", "Información de la Red Neuronal"))
        self.pushButtonSelectFiles.setText(_translate("MainWindow", "Presiona para seleccionar archivos"))
        self.label_9.setText(_translate("MainWindow", "Función de activación para la capa de salida es: la función logística."))
        self.pushButtonAboutProject.setText(_translate("MainWindow", "About This Project"))
        self.pushButtonGitHub.setText(_translate("MainWindow", "GitHub - Spam Classifier"))
        self.label_6.setText(_translate("MainWindow", "La red neuronal está compuesta por 3 capas."))
        self.label_7.setText(_translate("MainWindow", "La primera capa tiene 75,000 neuronas, la segunda 2 y la capa de salida tiene 1 neurona."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
